name: Weekly Scraper

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.2'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper/scraper.py

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/scraped_data.json
          if git diff --cached --quiet; then
            echo "No changes detected"
            exit 0
          fi
          git commit -m "Update scraper data ($(date))"
          git push